#####################################
# Taco-registry builder configuration
#####################################

# default configuration
default:
  domain: 192.168.201.2
  port: 4000
  # DEBUG, INFO, ERROR
  loglevel: DEBUG
  tmp: "/home/linus/tmp"

# database configuration
database:
  # postgres, mysql
  type: postgres
  host: exntu.kr
  port: 25432
  name: registry
  user: registry
  password: "registry1234$$"
  xargs:

# docker private registry configuration
registry:
  name: taco-registry
  insecure: true
  endpoint: "exntu.kr:25000"
  auth: "http://exntu.kr:38383/api/oauth/token"

# redis configuration
redis:
  endpoint: "exntu.kr:26379"

# clair configuration
clair:
  endpoint: "exntu.kr:26060"
