#####################################
# Taco-registry builder configuration
#####################################

# default configuration
default:
  domain: taco-registry-builder
  port: 4000
  # DEBUG, INFO, ERROR
  loglevel: DEBUG
  tmp: "/tmp"

# database configuration
database:
  # postgres, mysql
  type: postgres
  host: taco-db
  port: 5432
  name: registry
  user: registry
  password: "registry1234$$"
  xargs:

# docker private registry configuration
registry:
  name: taco-registry
  insecure: true
  endpoint: "taco-registry:5000"
  auth: "http://taco-registry-app:8080/api/oauth/token"

# redis configuration
redis:
  endpoint: "taco-redis:6379"

# clair configuration
clair:
  endpoint: "taco-clair:6060"

# minio configuration
minio:
  dir: /home/ubuntu/minio/data