// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-08-01 17:27:15.544412 +0900 KST m=+0.035782492

package docs

import (
	"bytes"
	"encoding/json"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/docker/build": {
            "get": {
                "description": "docker build by dockerfile api",
                "produces": [
                    "application/json"
                ],
                "summary": "docker build by dockerfile",
                "responses": {
                    "200": {}
                }
            }
        },
        "/docker/tag": {
            "get": {
                "description": "docker image tag",
                "produces": [
                    "application/json"
                ],
                "summary": "docker image tag",
                "responses": {
                    "200": {}
                }
            }
        },
        "/health": {
            "get": {
                "description": "builder의 health를 체크할 목적의 api",
                "produces": [
                    "application/json"
                ],
                "summary": "health check api",
                "responses": {
                    "200": {}
                }
            }
        },
        "/registry/catalog": {
            "get": {
                "description": "docker registry catalog api",
                "produces": [
                    "application/json"
                ],
                "summary": "docker registry catalog api",
                "responses": {
                    "200": {}
                }
            }
        },
        "/registry/repositories/{name}": {
            "get": {
                "description": "docker registry repositories api",
                "produces": [
                    "application/json"
                ],
                "summary": "docker registry repositories api",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Repository Name",
                        "name": "name",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "{{.Version}}",
	Host:        "{{.Host}}",
	BasePath:    "{{.BasePath}}",
	Schemes:     []string{},
	Title:       "{{.Title}}",
	Description: "{{.Description}}",
}

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
