basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /docker/build:
    get:
      description: docker build by dockerfile api
      produces:
      - application/json
      responses:
        "200": {}
      summary: docker build by dockerfile
  /docker/push:
    get:
      description: docker image push
      produces:
      - application/json
      responses:
        "200": {}
      summary: docker image push
  /docker/tag:
    get:
      description: docker image tag
      produces:
      - application/json
      responses:
        "200": {}
      summary: docker image tag
  /health:
    get:
      description: builder의 health를 체크할 목적의 api
      produces:
      - application/json
      responses:
        "200": {}
      summary: health check api
  /registry/catalog:
    get:
      description: docker registry catalog api
      produces:
      - application/json
      responses:
        "200": {}
      summary: docker registry catalog api
  /registry/repositories/{name}:
    get:
      description: docker registry repositories api
      parameters:
      - description: Repository Name
        in: path
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: docker registry repositories api
swagger: "2.0"
